### ISSUE TITLE
URL Template tag not working properly after adding Minio support

### ISSUE THREAD

**Issue by Mitrajeet-Golsangi** [theriverman/django-minio-backend#60]
I have a weird issue where the `django-minio-backend` package seems to have somehow sabotaged the `{% url %}` template tag in my project and now all the links point to the `MINIO_EXTERNAL_ENDPOINT`

I am using bootstrap 5 for styling with crispy forms (not sure if that is helpful)

template
```html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light static-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'my_view' %}" <!-- Points to localhost:9000 instead of localhost:8000 -->
            ><img src="{% static 'img/logo.png' %}" width="200" <!-- image loading properly -->
        /></a>
        <button
            class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbarResponsive"
            aria-controls="navbarResponsive"
            aria-expanded="false"
            aria-label="Toggle navigation"
        >
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                {% if request.user.is_authenticated %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'my_view' %}" ̥  <!-- Points to localhost:9000 instead of localhost:8000 -->
                        ><i class="fas fa-home"></i> Home
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                ...
```

Project URLs
```python
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api-auth/", include("rest_framework.urls")),
    path("", include("my_app.urls")),
    path("img/", include("upload_image.urls")),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
```

settings
```python
# Storage settings
STATIC_URL = "/static/"  # Ignored becuase of Minio. Keep for no django errors
MEDIA_URL = "/media/"  # Ignored becuase of Minio. Keep for no django errors

MINIO_CONSISTENCY_CHECK_ON_START = True
MINIO_BUCKET_CHECK_ON_SAVE = True
MINIO_ENDPOINT = "storage:9000"
MINIO_EXTERNAL_ENDPOINT = env("MINIO_EXTERNAL_ENDPOINT")

MINIO_EXTERNAL_ENDPOINT_USE_HTTPS = False
MINIO_USE_HTTPS = False

STORAGES = {
    "default": {
        "BACKEND": "django_minio_backend.models.MinioBackend",
    },
    "staticfiles": {
        "BACKEND": "django_minio_backend.models.MinioBackendStatic",
    },
}

MINIO_ACCESS_KEY = env("MINIO_ACCESS_KEY")
MINIO_SECRET_KEY = env("MINIO_SECRET_KEY")

MINIO_PRIVATE_BUCKETS = ["private-storage"]
MINIO_PUBLIC_BUCKETS = ["public-storage"]

MINIO_MEDIA_FILES_BUCKET = "media-root-storage"  # replacement for MEDIA_URL
MINIO_STATIC_FILES_BUCKET = "static-root-storage"  # replacement for STATIC_URL

MINIO_PRIVATE_BUCKETS.append(MINIO_MEDIA_FILES_BUCKET)
MINIO_PUBLIC_BUCKETS.append(MINIO_STATIC_FILES_BUCKET)
```
docker compose
```yaml
services:
  app:
    build:
      context: .
    develop:
      watch:
        - path: ./
          action: sync
          target: /app
        - path: ./Dockerfile
          action: rebuild
    ports:
      - '8000:8000'
    command: ['python', 'manage.py', 'runserver', '0.0.0.0:8000']
    # command: ["gunicorn", "--bind", "0.0.0.0:8000", "--log-level", "INFO", "--timeout", "5", "--threads", "10", "certification.wsgi"]
    depends_on:
      db:
        condition: service_healthy
      mailhog:
        condition: service_started
      redis:
        condition: service_started
    env_file:
      - .env

  storage:
    image: 'minio/minio:latest'
    ports:
      - '9001:9001'
      - '9000:9000' # API Endpoint required to be mapped since browser uses it
    command: server /data --console-address ":9001"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./.minio_data:/data
```
